# GOFmeas
*Ilaria Prosdocimi* (ilapro@ceh.ac.uk) and *Thomas Kjeldsen*

An R package to measure the Hosking and Wallis goodness of fit measure and the bivariate extension presented by Kjldsen and Prosdocimi. The measures are useful to quantify the goodness of fit to a set of possible distribution function for a sample of observations of region of influence. These are typically used in flood frequency analysis.

This package implements the measures discussed in: 


Kjeldsen T. R. and Prosdocimi I. (2015) A bivariate extension of the Hosking and Wallis goodness-of-fit measure for regional distributions. Water Resources Research. [DOI: 10.1002/2014WR015912](http://onlinelibrary.wiley.com/doi/10.1002/2014WR015912/abstract)

It can be loaded in R by typing

```r
library(devtools)
install_github("ilapros/GOFmeas")
library(GOFmeas)
``` 

The main function implemented in the package is the `GOFmeasures` function. 

**an example**

```r
library(GOFmeas)
amaxs <- list("river1" = c(192.92, 199.96, 178.90, 243.00, 182.93, 268.22, 263.52, 
                           166.82, 195.41, 251.65, 206.08, 174.34, 212.21, 253.74, 
                           195.69, 177.14, 193.33, 218.09, 233.69, 242.53, 191.09, 
                           243.20, 201.50, 206.58, 204.83, 226.49, 288.78), 
              "river2" = c(85.96, 87.15, 103.27, 117.50, 83.41, 83.12, 88.35,  89.98,
                           96.89, 77.54, 113.98,  99.61, 91.87, 89.30, 87.98, 117.62,
                           95.97, 80.20,  95.71,  87.70,145.84, 90.92, 84.53,  94.03,
                           79.07, 89.10,  85.84,  150.35),
              "river3" = c(183.56, 148.95, 175.88, 281.85, 392.15, 164.53, 199.99, 
                           163.22, 224.35, 264.79, 179.50, 201.19, 149.69, 247.65, 
                           237.57, 226.09, 197.34, 184.54, 235.66, 235.51, 452.03, 
                           209.25, 159.34, 350.17, 144.94, 220.09, 279.39, 288.47, 
                           236.48, 210.82, 267.95, 184.70, 269.45, 160.18, 204.24, 
                           271.61, 291.15, 136.23, 157.99, 262.34, 225.62, 204.39, 
                           227.14, 180.47, 216.58)
)

GOFmeasures(amaxs)
##            GLO    GEV     GNO     PE3
##   HW_GOF 0.6989 0.0460 -0.2572 -0.8083
##   KP_GOF 1.2918 0.0556  0.0578  0.8101
``` 
